name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 12 * * *'

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ">= 3.9"
      - name: lint
        run: |
          pip3 install black
          black --check protofuzz

  test:
    strategy:
      matrix:
        python:
          - "3.9"
          - "3.10"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python }}
      - name: deps
        run: sudo apt install -y protobuf-compiler
      - name: install
        run: python3 setup.py install
      - name: test
        run: python3 -m unittest discover protofuzz/tests
